### ISSUE TITLE
Лаб.2

### ISSUE THREAD

**Issue by lasbio** [KOKraynov/db-labs#2]
1.  Отсутствуют комментарии
2. task 5 - условие неправильно.
3.  task 9 - неточно, надо выбрать всех членов клуба, а не членов со  всеми их харатеристиками.
4.  task10 - неправильно. Выбраны не только члены клуба. + см. замечание 7.
5. task11 - неправильно. В задании указано "объединить", а у вас же произведено булево умножение таблиц.
6. task 14 - неточно, т.к. из сконструированной выборки не понятно какой из двух отобранных объектов дорогой, а какой дешевый.
7. В всех Ваших решениях введена сортировка, которая в заданиях отсутствует.  В ряде заданий, например,  TASK1 - это не сильно сказывается (меняется только порядок вывода записей), а в ряде заданий приводит к неправильному результату:
 - task 10 - отобраны первые 10 по алфавиту, что будет отличаться от первых 10 как в задании, т.е. если сделать по заданию, то по сути будут отобраны первые 10 зарегистрированных членов, т.к. memid - автоматически увеличивающее поле типа smallint unsigned;
 - task  11- SELECT max(..) FROM ....  возвращает одно значение. Зачем его сортировать?  На это будет просто затрачено впустую время.  Как минимум оптимизатор сервера, который готовит к выполнению команду, затратит время на анализ "нужно - не нужно" ORDER BY и т.д..

**Comment by lasbio** [comment]
1. Задание 9 - не точно. Нет смысла использовать date(joindate), т.к. '2012-09-01'  эквивалентно '2012-09-01 00:00:00', т.к. включают время.  Кроме того, если гость зарегистрирован после  латы отбора, то он будет присутствовать в списке членов клуба.
2. Задание 14 - не точно. Зачем использовать два условия на одно поле в WHERE, разве нельзя min и max нельзя посчитать в одном SELECT?

**Comment by KOKraynov** [comment]
Исправлена и показана на паре 30.10.

**Comment by lasbio** [comment]
Задание 9 - а если гость тоже зарегистрирован  2012-09-01?

**Comment by KOKraynov** [comment]
1. Задание 9, сделал отсев гостя, убрал лишнюю операцию.
2. Задание 14, поправил, чтобы мин и макс одним запросом считались.

**Comment by lasbio** [comment]
9 - не правильно.

**Comment by KOKraynov** [comment]
Поправил условие, как у сдавших это задание, на { joindate > "2012-08-31" }, но хочу заметить это - некорректно и ошибочно.
В задании четко написано ТЗ: "Выбрать всех членов клуба, зарегистрированных с сентября 2012 года". Это значит что они могут быть зарегистрированы в любое время, но дата должна быть с 1 сентября 2012 включительно по правилам русского языка. Условие joindate > "2012-08-31"  пропустит  дату 2012-08-31 08:44:42 так как она на более чем 8ч больше, но это все еще в августе. А значит корректно не joindate > "2012-08-31" , а joindate >= "2012-09-01". Как было ранее.

**Comment by KOKraynov** [comment]
9 - Правильно выставил условие даты и верно отсеял гостей.
