### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [KOKraynov/db-labs#3]
1. Задание 1 - не верно.  Например,  Farrell Junior   тоже будет отобран. И лучше использовать явное JOIN.
2.  Задание 2 - не верно.  Например, "теннисная коробка под мячи" тоже будет отобрана.
3. Задание 5 - не точно.  Не понятно какие корты покупал кто покупал. 
4. Задания 6, 7 не закончены.
5. Рекомендуется использовать заглавные буквы для KEYWORDS.

**Comment by lasbio** [comment]
Задание 1 - не точно.  Лучше использовать отдельные условия на имя и фамилию, чем на их объединение.  Объединение - лишнее время.
Задание 2 - не точно. зачем два разных условия на оно поле (facility)?  Разве нельзя записать это же в одном условии?
Задание 5 - см. замечание к 2.
Задания 6, 7 - не выполнены.

**Comment by KOKraynov** [comment]
1. Задание 1. Сделал отбор по имени и фамилии по отдельности
2. Задание 2. Добавил проверку, что  и теннис и корт.
3. Задание 5. Добавил вывод, колонку взятых кортов
4. Добавил задания 6 и 7

**Comment by lasbio** [comment]
5 - не верно. В задании нет условия "Tennis", зато есть условия на номера кортов.
6 - не точно. стоимость бронирования = стоимость единичной аренды (за слот == минимальное время) * количество слотов.

**Comment by KOKraynov** [comment]
5 - убрал теннис, добавил проверку на точный номер корта
6 - добавил в стоимость учет кол-ва слотов.

**Comment by lasbio** [comment]
более корректно делать через JOIN
